'use client';
import React, { useState } from 'react';
import SectionCard from './SectionCard';
import StatCard from './StatCard';
import SecurityScore from './SecurityScore';
import DomainOverview from './DomainOverview';
import SecuritySection from './SecuritySection';
import DNSSection from './DNSSection';
import SSLInfo from './SSLInfo';
import EmailSecuritySection from './EmailSecuritySection';
import TechStackSection from './TechStackSection';
import SubdomainsSection from './SubdomainsSection';
import VulnerabilitySection from './VulnerabilitySection';
import PortScanSection from './PortScanSection';
import CertificateAnalysisSection from './CertificateAnalysisSection';
import SecurityHeadersGradingSection from './SecurityHeadersGradingSection';
import PhishingDetectionSection from './PhishingDetectionSection';
import BlacklistCheckSection from './BlacklistCheckSection';
import DeepScanSection from './DeepScanSection';
import AnalyticsDashboard from './AnalyticsDashboard';
import SSLMonitoringSection from './SSLMonitoringSection';
import ComplianceSection from './ComplianceSection';
import UptimeSection from './UptimeSection';
import EnhancedSubdomainSection from './EnhancedSubdomainSection';
import SecurityScoreChart from './SecurityScoreChart';
import ShareResults from './ShareResults';
import RegistrarInfo from './RegistrarInfo';
import IPReputationSection from './IPReputationSection';
import LinkHealth from './LinkHealth';
import IPInfo from './IPInfo';
import CookieSecuritySection from './CookieSecuritySection';
import CSPSection from './CSPSection';
import MixedContentSection from './MixedContentSection';
import HSTSSection from './HSTSSection';
import DNSAnalysisSection from './DNSAnalysisSection';
import jsPDF from 'jspdf';

interface ResultsDisplayProps {
  results: any;
  sections: Array<{ id: string; label: string; icon: string }>;
  activeSection: string;
  setActiveSection: (section: string) => void;
}

export default function ResultsDisplay({ results, sections, activeSection, setActiveSection }: ResultsDisplayProps) {
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  if (!results) return null;

  const generatePDF = () => {
    setIsGeneratingPDF(true);
    
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const headerHeight = 25;
      const footerHeight = 15;
      let yPos = margin + headerHeight;
      
      const domainName = results.domainDetails?.hostname || 'Domain';
      
      // Helper function to add header on every page
      const addHeader = () => {
        // Blue header background
        pdf.setFillColor(59, 130, 246);
        pdf.rect(0, 0, pageWidth, headerHeight, 'F');
        
        // White text
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(16);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Domain Security Scan Report', margin, 12);
        
        // Domain name on the right
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'normal');
        const domainTextWidth = pdf.getTextWidth(domainName);
        pdf.text(domainName, pageWidth - margin - domainTextWidth, 12);
        
        // Reset text color
        pdf.setTextColor(0, 0, 0);
      };

      // Helper function to add footer on every page
      const addFooter = (pageNum: number, totalPages: number) => {
        pdf.setFontSize(8);
        pdf.setTextColor(128, 128, 128);
        pdf.setFont('helvetica', 'normal');
        const footerText = `${domainName} | Page ${pageNum} of ${totalPages} | Generated by Domain Security Scanner | Developed by krishnaneupane.com`;
        pdf.text(footerText, pageWidth / 2, pageHeight - 5, { align: 'center' });
      };

      // Helper function to add new page if needed
      const checkNewPage = (requiredHeight: number) => {
        if (yPos + requiredHeight > pageHeight - footerHeight - margin) {
          const currentPage = pdf.internal.pages.length - 1;
          addFooter(currentPage, pdf.internal.pages.length);
          pdf.addPage();
          addHeader();
          yPos = margin + headerHeight;
          return true;
        }
        return false;
      };

      // Helper function to add text with word wrap
      const addText = (text: string, fontSize: number, isBold: boolean = false, color: number[] = [0, 0, 0]) => {
        pdf.setFontSize(fontSize);
        pdf.setTextColor(color[0], color[1], color[2]);
        if (isBold) {
          pdf.setFont('helvetica', 'bold');
        } else {
          pdf.setFont('helvetica', 'normal');
        }
        
        const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
        lines.forEach((line: string) => {
          checkNewPage(7);
          pdf.text(line, margin, yPos);
          yPos += 7;
        });
      };

      // Helper function to add section header with domain name
      const addSectionHeader = (title: string, color: number[] = [59, 130, 246]) => {
        checkNewPage(15);
        // Section divider line
        pdf.setDrawColor(color[0], color[1], color[2]);
        pdf.setLineWidth(0.5);
        pdf.line(margin, yPos - 2, pageWidth - margin, yPos - 2);
        yPos += 3;
        
        // Section title with domain context
        pdf.setFontSize(14);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(color[0], color[1], color[2]);
        pdf.text(`${title} - ${domainName}`, margin, yPos);
        yPos += 8;
        
        // Reset text color
        pdf.setTextColor(0, 0, 0);
      };

      // Helper function to format object data
      const formatObject = (obj: any, indent: number = 0): string => {
        if (!obj || typeof obj !== 'object') return String(obj || 'N/A');
        if (Array.isArray(obj)) {
          return obj.length > 0 ? obj.map((item, i) => `${i + 1}. ${formatObject(item, indent + 1)}`).join('\n') : 'None';
        }
        return Object.entries(obj)
          .map(([key, value]) => {
            const prefix = '  '.repeat(indent);
            if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
              return `${prefix}${key}:\n${formatObject(value, indent + 1)}`;
            }
            return `${prefix}${key}: ${formatObject(value, indent)}`;
          })
          .join('\n');
      };

      // Add header to first page
      addHeader();
      
      // Title Section
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(59, 130, 246);
      pdf.text(`Security Analysis Report for ${domainName}`, margin, yPos);
      yPos += 10;
      
      pdf.setTextColor(0, 0, 0);

      // Domain Information Section
      addSectionHeader('DOMAIN INFORMATION', [59, 130, 246]);
      addText(`Domain: ${domainName}`, 12, true);
      addText(`Scan Date: ${new Date().toLocaleString()}`, 11);
      if (results.domainDetails?.ip) {
        addText(`IP Address: ${results.domainDetails.ip}`, 11);
      }
      if (results.securityScore !== undefined) {
        addText(`Security Score: ${results.securityScore}/100`, 12, true, 
          results.securityScore >= 80 ? [34, 197, 94] : results.securityScore >= 60 ? [234, 179, 8] : [239, 68, 68]);
      }
      yPos += 5;

      // Executive Summary Section
      addSectionHeader('EXECUTIVE SUMMARY', [59, 130, 246]);
      
      const summary = [];
      if (results.securityScore !== undefined) {
        summary.push(`Security Score: ${results.securityScore}/100`);
      }
      if (results.vulnerabilities?.length) {
        summary.push(`Vulnerabilities Found: ${results.vulnerabilities.length}`);
      }
      if (results.ssl?.valid !== undefined) {
        summary.push(`SSL Certificate: ${results.ssl.valid ? 'Valid' : 'Invalid'}`);
      }
      if (results.subdomains?.length) {
        summary.push(`Subdomains Discovered: ${results.subdomains.length}`);
      }
      addText(summary.join(' | '), 11);
      yPos += 8;

      // Security Analysis Section
      if (results.security) {
        addSectionHeader('SECURITY HEADERS ANALYSIS', [59, 130, 246]);
        if (results.security.headers) {
          const headers = Object.entries(results.security.headers)
            .map(([key, value]: [string, any]) => `${key}: ${value.present ? 'Present' : 'Missing'}`)
            .join('\n');
          addText(headers, 10);
        }
        yPos += 5;
      }

      // SSL/TLS Information Section
      if (results.ssl) {
        addSectionHeader('SSL/TLS CERTIFICATE ANALYSIS', [59, 130, 246]);
        addText(`Valid: ${results.ssl.valid ? 'Yes' : 'No'}`, 11);
        if (results.ssl.issuer) addText(`Issuer: ${results.ssl.issuer}`, 10);
        if (results.ssl.validFrom) addText(`Valid From: ${results.ssl.validFrom}`, 10);
        if (results.ssl.validTo) addText(`Valid To: ${results.ssl.validTo}`, 10);
        if (results.ssl.protocol) addText(`Protocol: ${results.ssl.protocol}`, 10);
        yPos += 5;
      }

      // DNS Information Section
      if (results.dns) {
        addSectionHeader('DNS RECORDS ANALYSIS', [59, 130, 246]);
        const dnsInfo = formatObject(results.dns, 0);
        const dnsLines = pdf.splitTextToSize(dnsInfo, pageWidth - 2 * margin);
        dnsLines.forEach((line: string) => {
          checkNewPage(7);
          pdf.setFontSize(9);
          pdf.text(line, margin, yPos);
          yPos += 5;
        });
        yPos += 3;
      }

      // Vulnerabilities Section
      if (results.vulnerabilities && results.vulnerabilities.length > 0) {
        addSectionHeader('VULNERABILITIES DETECTED', [239, 68, 68]);
        results.vulnerabilities.forEach((vuln: any, index: number) => {
          checkNewPage(15);
          addText(`${index + 1}. ${vuln.name || vuln.title || 'Vulnerability'}`, 11, true);
          if (vuln.severity) addText(`Severity: ${vuln.severity}`, 10);
          if (vuln.description) addText(`Description: ${vuln.description}`, 10);
          yPos += 3;
        });
        yPos += 3;
      }

      // Subdomains Section
      if (results.subdomains && results.subdomains.length > 0) {
        addSectionHeader('SUBDOMAINS DISCOVERED', [59, 130, 246]);
        const subdomainText = results.subdomains.slice(0, 20).join(', ');
        addText(subdomainText, 10);
        if (results.subdomains.length > 20) {
          addText(`... and ${results.subdomains.length - 20} more`, 10);
        }
        yPos += 5;
      }

      // Email Security Section
      if (results.emailSecurity) {
        addSectionHeader('EMAIL SECURITY ANALYSIS', [59, 130, 246]);
        const emailInfo = formatObject(results.emailSecurity, 0);
        const emailLines = pdf.splitTextToSize(emailInfo, pageWidth - 2 * margin);
        emailLines.forEach((line: string) => {
          checkNewPage(7);
          pdf.setFontSize(9);
          pdf.text(line, margin, yPos);
          yPos += 5;
        });
        yPos += 3;
      }

      // Recommendations Section
      if (results.recommendations && results.recommendations.length > 0) {
        addSectionHeader('SECURITY RECOMMENDATIONS', [34, 197, 94]);
        results.recommendations.forEach((rec: string, index: number) => {
          checkNewPage(10);
          addText(`${index + 1}. ${rec}`, 10);
          yPos += 2;
        });
        yPos += 3;
      }

      // Add additional sections with domain context
      
      // Technology Stack Section
      if (results.techStack) {
        addSectionHeader('TECHNOLOGY STACK', [59, 130, 246]);
        const techInfo = formatObject(results.techStack, 0);
        const techLines = pdf.splitTextToSize(techInfo, pageWidth - 2 * margin);
        techLines.forEach((line: string) => {
          checkNewPage(7);
          pdf.setFontSize(9);
          pdf.text(line, margin, yPos);
          yPos += 5;
        });
        yPos += 3;
      }

      // Compliance Section
      if (results.compliance) {
        addSectionHeader('COMPLIANCE & PRIVACY', [34, 197, 94]);
        const complianceInfo = formatObject(results.compliance, 0);
        const complianceLines = pdf.splitTextToSize(complianceInfo, pageWidth - 2 * margin);
        complianceLines.forEach((line: string) => {
          checkNewPage(7);
          pdf.setFontSize(9);
          pdf.text(line, margin, yPos);
          yPos += 5;
        });
        yPos += 3;
      }

      // IP Reputation Section
      if (results.ipReputation) {
        addSectionHeader('IP REPUTATION ANALYSIS', [59, 130, 246]);
        const ipInfo = formatObject(results.ipReputation, 0);
        const ipLines = pdf.splitTextToSize(ipInfo, pageWidth - 2 * margin);
        ipLines.forEach((line: string) => {
          checkNewPage(7);
          pdf.setFontSize(9);
          pdf.text(line, margin, yPos);
          yPos += 5;
        });
        yPos += 3;
      }

      // Registrar Information Section
      if (results.whois) {
        addSectionHeader('REGISTRAR INFORMATION', [59, 130, 246]);
        const whoisInfo = formatObject(results.whois, 0);
        const whoisLines = pdf.splitTextToSize(whoisInfo, pageWidth - 2 * margin);
        whoisLines.forEach((line: string) => {
          checkNewPage(7);
          pdf.setFontSize(9);
          pdf.text(line, margin, yPos);
          yPos += 5;
        });
        yPos += 3;
      }

      // Port Scan Section
      if (results.portScan) {
        addSectionHeader('PORT SCAN RESULTS', [59, 130, 246]);
        const portInfo = formatObject(results.portScan, 0);
        const portLines = pdf.splitTextToSize(portInfo, pageWidth - 2 * margin);
        portLines.forEach((line: string) => {
          checkNewPage(7);
          pdf.setFontSize(9);
          pdf.text(line, margin, yPos);
          yPos += 5;
        });
        yPos += 3;
      }

      // Add final note with developer credit
      checkNewPage(20);
      yPos += 10;
      pdf.setDrawColor(200, 200, 200);
      pdf.setLineWidth(0.5);
      pdf.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 10;
      
      pdf.setFontSize(9);
      pdf.setTextColor(100, 100, 100);
      pdf.setFont('helvetica', 'italic');
      pdf.text('This report was generated by Domain Security Scanner', margin, yPos);
      yPos += 6;
      pdf.text('Developed by krishnaneupane.com', margin, yPos);
      yPos += 6;
      pdf.setFontSize(7);
      pdf.setTextColor(150, 150, 150);
      pdf.text(`For more information, visit: https://krishnaneupane.com`, margin, yPos);

      // Add footer to all pages
      const totalPages = pdf.internal.pages.length - 1;
      for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        addFooter(i, totalPages);
      }

      // Save PDF
      const fileName = `${domainName.replace(/[^a-z0-9]/gi, '_')}_security_report_${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(fileName);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating PDF. Please try again.');
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  return (
    <div className="space-y-6 animate-scale-in">
      {/* Results Header - Impressive Design */}
      <div className="relative group mb-12">
        {/* Glow Effect */}
        <div className="absolute -inset-2 bg-gradient-to-r from-blue-600 via-cyan-500 to-teal-600 rounded-3xl blur-2xl opacity-20 group-hover:opacity-30 transition duration-1000 animate-pulse"></div>
        
        {/* Main Card */}
        <div className="relative backdrop-blur-2xl bg-white/90 dark:bg-slate-900/90 border-2 border-slate-200/60 dark:border-slate-800/60 rounded-3xl shadow-2xl p-8 md:p-12 hover:shadow-3xl transition-all duration-500">
          <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6 mb-6">
            <div className="flex-1">
              <div className="flex items-center space-x-4 mb-6">
                <div className="relative">
                  <div className="absolute inset-0 bg-gradient-to-r from-blue-500 via-cyan-500 to-teal-500 rounded-2xl blur-lg opacity-50 animate-pulse"></div>
                  <div className="relative w-16 h-16 bg-gradient-to-br from-blue-500 via-cyan-500 to-teal-500 rounded-2xl flex items-center justify-center shadow-2xl">
                    <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                    </svg>
                  </div>
                </div>
                <div>
                  <h2 className="text-3xl md:text-4xl font-black text-slate-900 dark:text-slate-100 mb-2">
                    <span className="bg-gradient-to-r from-blue-600 via-cyan-600 to-teal-600 dark:from-blue-400 dark:via-cyan-400 dark:to-teal-400 bg-clip-text text-transparent">
                      {results.domainDetails?.hostname || 'Scan Results'}
                    </span>
                  </h2>
                  <p className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
                    Comprehensive Security Analysis Report
                  </p>
                  <p className="text-xs text-slate-400 dark:text-slate-500 mt-1">
                    Scanned on {new Date().toLocaleString()}
                  </p>
                </div>
              </div>
              
              {/* Quick Stats Grid */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {results.securityScore !== undefined && (
                  <div className="relative group/stat">
                    <div className="absolute -inset-0.5 bg-gradient-to-r from-blue-500 via-cyan-500 to-teal-500 rounded-xl blur opacity-20 group-hover/stat:opacity-30 transition"></div>
                    <div className="relative bg-white/80 dark:bg-slate-800/80 backdrop-blur-sm border border-slate-200/60 dark:border-slate-700/60 rounded-xl p-4 shadow-lg">
                      <div className="text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-1">
                        Security Score
                      </div>
                      <div className={`text-3xl font-black ${
                        results.securityScore >= 80 ? 'text-green-600 dark:text-green-400' :
                        results.securityScore >= 60 ? 'text-yellow-600 dark:text-yellow-400' :
                        'text-red-600 dark:text-red-400'
                      }`}>
                        {results.securityScore}
                        <span className="text-lg text-slate-400">/100</span>
                      </div>
                    </div>
                  </div>
                )}
                {results.vulnerabilities && (
                  <div className="relative group/stat">
                    <div className="absolute -inset-0.5 bg-gradient-to-r from-blue-500 via-cyan-500 to-teal-500 rounded-xl blur opacity-20 group-hover/stat:opacity-30 transition"></div>
                    <div className="relative bg-white/80 dark:bg-slate-800/80 backdrop-blur-sm border border-slate-200/60 dark:border-slate-700/60 rounded-xl p-4 shadow-lg">
                      <div className="text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-1">
                        Vulnerabilities
                      </div>
                      <div className={`text-3xl font-black ${
                        results.vulnerabilities.length === 0 ? 'text-green-600 dark:text-green-400' :
                        results.vulnerabilities.length < 5 ? 'text-yellow-600 dark:text-yellow-400' :
                        'text-red-600 dark:text-red-400'
                      }`}>
                        {results.vulnerabilities.length}
                      </div>
                    </div>
                  </div>
                )}
                {results.subdomains && (
                  <div className="relative group/stat">
                    <div className="absolute -inset-0.5 bg-gradient-to-r from-blue-500 via-cyan-500 to-teal-500 rounded-xl blur opacity-20 group-hover/stat:opacity-30 transition"></div>
                    <div className="relative bg-white/80 dark:bg-slate-800/80 backdrop-blur-sm border border-slate-200/60 dark:border-slate-700/60 rounded-xl p-4 shadow-lg">
                      <div className="text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-1">
                        Subdomains
                      </div>
                      <div className="text-3xl font-black text-blue-600 dark:text-blue-400">
                        {results.subdomains.length}
                      </div>
                    </div>
                  </div>
                )}
                {results.ssl?.valid !== undefined && (
                  <div className="relative group/stat">
                    <div className="absolute -inset-0.5 bg-gradient-to-r from-blue-500 via-cyan-500 to-teal-500 rounded-xl blur opacity-20 group-hover/stat:opacity-30 transition"></div>
                    <div className="relative bg-white/80 dark:bg-slate-800/80 backdrop-blur-sm border border-slate-200/60 dark:border-slate-700/60 rounded-xl p-4 shadow-lg">
                      <div className="text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-1">
                        SSL Status
                      </div>
                      <div className={`text-2xl font-black ${
                        results.ssl.valid ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'
                      }`}>
                        {results.ssl.valid ? '✓ Valid' : '✗ Invalid'}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
            
            {/* Action Buttons */}
            <div className="flex flex-wrap gap-3">
              <ShareResults domain={results.domainDetails?.hostname || ''} />
              <button
                onClick={generatePDF}
                disabled={isGeneratingPDF}
                className="relative px-6 py-3 bg-gradient-to-r from-blue-600 via-cyan-600 to-teal-600 hover:from-blue-700 hover:via-cyan-700 hover:to-teal-700 text-white rounded-xl font-bold shadow-xl hover:shadow-2xl transition-all duration-300 transform hover:scale-105 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 overflow-hidden group"
              >
                {isGeneratingPDF ? (
                  <>
                    <svg className="w-5 h-5 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                    </svg>
                    <span>Generating...</span>
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    <span>Download PDF</span>
                  </>
                )}
              </button>
              <button
                className="px-6 py-3 bg-gradient-to-r from-slate-600 to-slate-700 hover:from-slate-700 hover:to-slate-800 text-white rounded-xl font-bold shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105 active:scale-95 flex items-center gap-2"
                onClick={() => {
                  const dataStr = JSON.stringify(results, null, 2);
                  const dataBlob = new Blob([dataStr], { type: 'application/json' });
                  const url = URL.createObjectURL(dataBlob);
                  const link = document.createElement('a');
                  link.href = url;
                  link.download = `${results.domainDetails?.hostname || 'domain'}_scan_report.json`;
                  link.click();
                  URL.revokeObjectURL(url);
                }}
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                </svg>
                <span>JSON</span>
              </button>
            </div>
          </div>

          {/* Section Navigation */}
          <div className="border-t border-slate-200/60 dark:border-slate-700/60 pt-4 mt-6">
            <nav className="flex space-x-2 overflow-x-auto pb-2" aria-label="Sections">
              {sections.map((section) => (
                <button
                  key={section.id}
                  onClick={() => {
                    setActiveSection(section.id);
                    document.getElementById(`section-${section.id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
                  }}
                  className={`px-4 py-2.5 text-sm font-bold whitespace-nowrap rounded-xl transition-all ${
                    activeSection === section.id
                      ? 'bg-gradient-to-r from-blue-600 via-cyan-600 to-teal-600 text-white shadow-lg transform scale-105'
                      : 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700'
                  }`}
                >
                  <span className="mr-2">{section.icon}</span>
                  {section.label}
                </button>
              ))}
            </nav>
          </div>
        </div>
      </div>

      {/* Results Content */}
      <div className="space-y-6">
        {/* Overview Section */}
        <SectionCard id="section-overview" title="Overview" icon="📊" collapsible defaultExpanded={true}>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
            {results.securityScore !== undefined && (
              <div>
                <SecurityScore 
                  score={results.securityScore} 
                  riskAssessment={results.riskAssessment}
                  recommendations={results.recommendations}
                />
              </div>
            )}
            {results.domainDetails && (
              <div>
                <DomainOverview details={results.domainDetails} ssl={results.ssl} emails={results.emails} />
              </div>
            )}
          </div>
          {results.securityScore !== undefined && (
            <div className="mt-6">
              <SecurityScoreChart
                score={results.securityScore}
                breakdown={{
                  ssl: results.ssl?.valid ? 100 : 0,
                  headers: results.security?.headers ? 
                    (Object.values(results.security.headers).filter((h: any) => h.present).length / Object.keys(results.security.headers).length) * 100 : 0,
                  cookies: results.cookies?.score || 0,
                  csp: results.csp?.score || 0,
                  emailSecurity: results.emailSecurity?.score || 0,
                  dns: results.dnsAnalysis?.score || 0,
                  mixedContent: results.mixedContent?.score || 0,
                  hsts: results.hsts?.preloaded ? 100 : (results.hsts?.eligible ? 80 : 0),
                  protocols: results.security?.protocols ? 
                    ((results.security.protocols.tlsStatus === 'secure' ? 50 : 0) + 
                     (results.security.protocols.cipherStatus === 'secure' ? 50 : 0)) : 0,
                  ipReputation: results.ipReputation?.reputationScore || 0,
                }}
              />
            </div>
          )}
        </SectionCard>

        {/* Security Section */}
        <SectionCard id="section-security" title="Security Analysis" icon="🔒" collapsible defaultExpanded={true}>
          <div className="space-y-4">
            {results.security && <SecuritySection headers={results.security.headers} protocols={results.security.protocols} />}
            {results.cookies && <CookieSecuritySection cookies={results.cookies} />}
            {results.csp && <CSPSection csp={results.csp} />}
            {results.mixedContent && <MixedContentSection mixedContent={results.mixedContent} />}
            {results.hsts && <HSTSSection hsts={results.hsts} />}
            {results.headersGrading && <SecurityHeadersGradingSection headersGrading={results.headersGrading} />}
          </div>
        </SectionCard>

        {/* DNS Section */}
        <SectionCard id="section-dns" title="DNS Analysis" icon="🌐" collapsible defaultExpanded={true}>
          <div className="space-y-4">
            {results.dns && <DNSSection dns={results.dns} dnssec={results.dnssec} rawDns={results.rawDns} />}
            {results.dnsAnalysis && <DNSAnalysisSection dnsAnalysis={results.dnsAnalysis} />}
          </div>
        </SectionCard>

        {/* SSL/TLS Section */}
        <SectionCard id="section-ssl" title="SSL/TLS Analysis" icon="🔐" collapsible defaultExpanded={true}>
          <div className="space-y-4">
            {results.ssl && <SSLInfo ssl={results.ssl} vulnerabilities={results.vulnerabilities} brokenLinks={results.brokenLinks} />}
            {results.certificateAnalysis && (
              <CertificateAnalysisSection 
                certificateAnalysis={results.certificateAnalysis}
                certificateTransparency={results.certificateTransparency}
              />
            )}
            {results.sslMonitoring && <SSLMonitoringSection sslMonitoring={results.sslMonitoring} />}
          </div>
        </SectionCard>

        {/* Additional Sections */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {results.emailSecurity && (
            <SectionCard title="Email Security" icon="📧">
              <EmailSecuritySection emailSecurity={results.emailSecurity} />
            </SectionCard>
          )}
          {results.techStack && (
            <SectionCard title="Technology Stack" icon="⚙️">
              <TechStackSection techStack={results.techStack} />
            </SectionCard>
          )}
        </div>

        {/* Compliance Section */}
        <SectionCard id="section-compliance" title="Compliance & Privacy" icon="✅" collapsible defaultExpanded={true}>
          <div className="space-y-4">
            {results.compliance && <ComplianceSection compliance={results.compliance} />}
          </div>
        </SectionCard>

        {/* Advanced Section */}
        <SectionCard id="section-advanced" title="Advanced Analysis" icon="🔬" collapsible defaultExpanded={true}>
          <div className="space-y-6">
            {results.subdomains && results.subdomains.length > 0 && (
              <SubdomainsSection subdomains={results.subdomains} />
            )}
            {results.enhancedSubdomains && results.subdomainAnalysis && (
              <EnhancedSubdomainSection 
                enhancedSubdomains={results.enhancedSubdomains}
                subdomainAnalysis={results.subdomainAnalysis}
              />
            )}
            {results.vulnerabilities && results.vulnerabilities.length > 0 && (
              <VulnerabilitySection threats={results.threats} vulnerabilities={results.vulnerabilities} />
            )}
            {results.portScan && <PortScanSection portScan={results.portScan} />}
            {results.phishingDetection && <PhishingDetectionSection phishingDetection={results.phishingDetection} />}
            {results.blacklistCheck && <BlacklistCheckSection blacklistCheck={results.blacklistCheck} />}
            {results.deepScan && <DeepScanSection deepScan={results.deepScan} />}
          </div>
        </SectionCard>

        {/* Performance & Monitoring */}
        <SectionCard id="section-performance" title="Performance & Monitoring" icon="⚡" collapsible defaultExpanded={true}>
          <div className="space-y-4">
            {results.uptimeMonitoring && <UptimeSection uptimeMonitoring={results.uptimeMonitoring} />}
            <AnalyticsDashboard currentScan={results} />
          </div>
        </SectionCard>

        {/* Additional Info */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {results.whois && (
            <SectionCard title="Registrar Information" icon="📋">
              <RegistrarInfo whois={results.whois} />
            </SectionCard>
          )}
          {results.ipReputation && (
            <SectionCard title="IP Reputation" icon="🌍">
              <IPReputationSection ipReputation={results.ipReputation} />
            </SectionCard>
          )}
        </div>

        {results.brokenLinks && results.brokenLinks.length > 0 && (
          <SectionCard title="Link Health" icon="🔗">
            <LinkHealth brokenLinks={results.brokenLinks} />
          </SectionCard>
        )}

        {results.ipServices && results.ipServices.length > 0 && (
          <SectionCard title="IP Information" icon="📍">
            <IPInfo ipServices={results.ipServices} />
          </SectionCard>
        )}
      </div>
    </div>
  );
}
